# Generated by Django 4.2.5 on 2023-10-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='services', verbose_name='Image Upload'),
        ),
    ]
